name: Build APK with Docker
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Build with Docker
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_cmd: buildozer android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pixel-editor-apk
          path: bin/*.apk
